//Auth
export const USER_LOADED = "USER_LOADED";
export const USER_LOADED_FAIL = "USER_LOADED_FAIL";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";
export const LOGOUT = "LOGOUT";

export const AUTH_ERROR = "AUTH_ERROR";
export const RECOVER_REQUEST_SUCCESS = "RECOVER_REQUEST_SUCCESS";
export const RECOVER_REQUEST_FAILED = "RECOVER_REQUEST_FAILED";
export const PASSWORD_CHANGED = "PASSWORD_CHANGED";
export const PASSWORD_CHANGE_FAIL = "PASSWORD_CHANGE_FAIL";

//USer
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

//ALERT
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

//Product
export const ALL_PRODUCT_LOADED = "ALL_PRODUCT_LOADED";
export const ALL_PRODUCT_LOADED_FAIL = "ALL_PRODUCT_LOADED_FAIL";
export const PRODUCT_LOADED = "PRODUCT_LOADED";
export const PRODUCT_LOADED_FAIL = "PRODUCT_LOADED_FAIL";
export const PRODUCT_ADDED = "PRODUCT_ADDED";
export const PRODUCT_ADD_FAIL = "PRODUCT_ADD_FAIL";
export const PRODUCT_UPDATED = "PRODUCT_UPDATED";
export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL";

//Category
export const ALL_CATEGORY_LOADED = "ALL_CATEGORY_LOADED";
export const ALL_CATEGORY_LOADED_FAIL = "ALL_CATEGORY_LOADED_FAIL";

//Gallery
export const ALL_GALLERY_LOADED = "ALL_GALLERY_LOADED";
export const ALL_GALLERY_LOADED_FAIL = "ALL_GALLERY_LOADED_FAIL";
export const GALLERY_LOADED = "GALLERY_LOADED";
export const GALLERY_LOADED_FAIL = "GALLERY_LOADED_FAIL";
export const IMAGE_UPLOADED = "IMAGE_UPLOADED";
export const IMAGE_UPLOAD_FAIL = "IMAGE_UPLOAD_FAIL";
export const IMAGE_DELETED = "IMAGE_DELETED";
export const IMAGE_DEL_FAIL = "IMAGE_DEL_FAIL";
